# Generated by Django 3.1.2 on 2020-10-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followed',
            new_name='following',
        ),
    ]
